baseurl: "/"
languageCode: "en-us"
title: "Roman BÃ¶hm's Website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Posts
      url: "posts/"
      weight: 2
    - name: TIL
      url: "/tags/til/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4

params:
  description: "Website of Roman BÃ¶hm"
  footer: "&copy; Roman BÃ¶hm 2021 -- {Year} // [Github](https://github.com/romanboehm) // [Twitter](https://twitter.com/0xromanboehm) // [LinkedIn](https://www.linkedin.com/in/ðŸ–¥%EF%B8%8F-roman-bÃ¶hm-837946175/)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true